name: topopt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=21.3.1
  - fenics=2019.1.0
  - scipy=1.7.3
  - numpy=1.22.0
  - matplotlib=3.5.1
  - mpi4py=3.1.3
  - cyipopt=1.1.0
  - superlu_dist
  - pip:
      - git+https://github.com/dolfin-adjoint/pyadjoint.git@2019.1.2