name: topopt
channels:
  - conda-forge
  - defaults
dependencies:
  - ipopt
  - fenics-dolfin
  - meshio
  - h5py
  - matplotlib
  - python=3.10
  - numpy
  - pip:
      - cyipopt
      - git+https://github.com/dolfin-adjoint/pyadjoint.git@2019.1.2
      - scikit-umfpack
