name: testing TopOpt

on: [push]

jobs:
  build:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3

      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          environment-name: root
      
      - name: Test with pytest
        run: |
          conda install pytest
          pytest
